{
 "title": "Cilium Policy Verdicts",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "query_result(hubble_policy_verdicts_total)"
    }
   },
   {
    "name": "workload",
    "query": {
     "query": "query_result(hubble_policy_verdicts_total)"
    }
   },
   {
    "name": "source_namespace",
    "label": "source namespace",
    "query": {
     "query": "label_values(hubble_policy_verdicts_total, source_namespace)"
    }
   },
   {
    "name": "source",
    "label": "source workload",
    "query": {
     "query": "label_values(hubble_policy_verdicts_total, source)"
    }
   },
   {
    "name": "destination_namespace",
    "label": "destination namespace",
    "query": {
     "query": "label_values(hubble_policy_verdicts_total, destination_namespace)"
    }
   },
   {
    "name": "destination",
    "label": "destination workload",
    "query": {
     "query": "label_values(hubble_policy_verdicts_total, destination)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ingress Policy Verdict Rate per Minute by Match Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (match) (rate(hubble_policy_verdicts_total{direction=\"ingress\", destination_namespace=~\"$namespace\", destination=~\"$workload\", source_namespace=~\"$source_namespace\", source=~\"$source\"}[$__rate_interval])) * 60",
     "legendFormat": "{{match}}"
    }
   ]
  },
  {
   "title": "Egress Policy Verdict Rate per Minute by Match Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (match) (rate(hubble_policy_verdicts_total{direction=\"egress\", source_namespace=~\"$namespace\", source=~\"$workload\", destination_namespace=~\"$destination_namespace\", destination=~\"$destination\"}[$__rate_interval])) * 60",
     "legendFormat": "{{match}}"
    }
   ]
  },
  {
   "title": "Ingress Policy Verdict Rate per Minute by Action",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (action) (rate(hubble_policy_verdicts_total{direction=\"ingress\", destination_namespace=~\"$namespace\", destination=~\"$workload\", source_namespace=~\"$source_namespace\", source=~\"$source\"}[$__rate_interval])) * 60",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Egress Policy Verdict Rate per Minute by Action",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (action) (rate(hubble_policy_verdicts_total{direction=\"egress\", source_namespace=~\"$namespace\", source=~\"$workload\", destination_namespace=~\"$destination_namespace\", destination=~\"$destination\"}[$__rate_interval])) * 60",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Current Ingress Policy Verdict Rate Per Minute",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (source_namespace, source, destination_namespace, destination, match, action) (rate(hubble_policy_verdicts_total{direction=\"ingress\", destination_namespace=~\"$namespace\", destination=~\"$workload\", source_namespace=~\"$source_namespace\", source=~\"$source\"}[$__rate_interval])) * 60",
     "legendFormat": "source: {{source_namespace}}/{{source}} destination: {{destination_namespace}}/{{destination}} match: {{match}} action: {{action}}"
    }
   ]
  },
  {
   "title": "Current Egress Policy Verdict Rate Per Minute",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (destination_namespace, destination, source_namespace, source, match, action) (rate(hubble_policy_verdicts_total{direction=\"egress\", source_namespace=~\"$namespace\", source=~\"$workload\", destination_namespace=~\"$destination_namespace\", destination=~\"$destination\"}[$__rate_interval])) * 60",
     "legendFormat": "destination: {{destination_namespace}}/{{destination}} source:  {{source_namespace}}/{{source}} match: {{match}} action: {{action}}"
    }
   ]
  }
 ]
}